# Generated by Django 4.1 on 2026-03-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='painting',
            name='category',
            field=models.CharField(choices=[('oil', 'Oil on Canvas'), ('watercolor', 'Watercolor'), ('acrylic', 'Acrylic'), ('digital', 'Digital Art'), ('mixed', 'Mixed Media')], default='oil', max_length=50),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='image_path',
            field=models.CharField(blank=True, help_text='Enter image URL or path', max_length=500, null=True),
        ),
    ]
