# Generated by Django 4.1 on 2026-03-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_painting_status_alter_painting_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
