# Generated by Django 4.1 on 2026-03-09 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0003_painting_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='likes',
        ),
        migrations.AddField(
            model_name='painting',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_paintings', to=settings.AUTH_USER_MODEL),
        ),
    ]
